/**
 * DatalabsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class CollectionCuratorController extends BaseController {
  /**
   * Creating a collection for Collection Curator
   *
   * @param body body
   * @return Response from the API call
   */
  async createACollection(
    body: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest(
      'POST',
      '/apps/collection-creator/workspace/collection'
    );
    const mapped = req.prepareArgs({ body: [body, unknown()] });
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }
}
