/**
 * DatalabsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class ServicesController extends BaseController {
  /**
   * Authentication
   *
   * @return Response from the API call
   */
  async authentication(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/services/auth-token');
    return req.callAsJson(unknown(), requestOptions);
  }
}
