/**
 * DatalabsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { passThroughInterceptor } from './core';
import { AuthenticatorInterface } from './core';

/** None authentication provider */
export const noneAuthenticationProvider = () => passThroughInterceptor;

export const customAuthenticationProvider = ({
}: {
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }

    return (request, options, next) => {

      return next(request, options);
    };
  };
};
